"""GPU Sizing & Cloud Savings Calculator.

Streamlit front-end modeled on AMD's AI Cost Calculator (tokenomics.amd.com):
  Step 1 (sidebar):  your AI usage — token intensity, growth, cloud pricing
  Step 2 (main):     your results — GPU sizing, TCO vs cloud, break-even, savings

Run:  streamlit run app.py --server.port 8765 --server.address 0.0.0.0
"""

from __future__ import annotations

import io

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from gpu_sizing.calc import (
    CloudPricing,
    Demand,
    GpuSpec,
    Ownership,
    simulate,
    sensitivity,
)
from gpu_sizing.data import CLOUD_MODELS, GPU_PRESETS, INTENSITY_PRESETS

st.set_page_config(
    page_title="GPU Sizing & Cloud Savings",
    page_icon="🖥️",
    layout="wide",
    initial_sidebar_state="expanded",
)

CLOUD_BY_KEY = {m["key"]: m for m in CLOUD_MODELS}
GPU_BY_KEY = {g["key"]: g for g in GPU_PRESETS}


def usd(x: float) -> str:
    if x is None or x != x:
        return "—"
    neg = x < 0
    x = abs(x)
    if x >= 1_000_000:
        s = f"${x/1_000_000:,.2f}M"
    elif x >= 10_000:
        s = f"${x:,.0f}"
    else:
        s = f"${x:,.2f}"
    return "-" + s if neg else s


def usd_full(x: float) -> str:
    return f"${x:,.2f}"


# =====================================================================
# STEP 1 — Your AI usage (sidebar)
# =====================================================================
sb = st.sidebar
sb.title("🖥️ GPU Sizing")
sb.caption("Cloud vs on-prem inference — TCO, break-even, savings")
sb.markdown("---")
sb.header("1 · Your AI usage")

preset = sb.selectbox(
    "Usage intensity (per user)",
    list(INTENSITY_PRESETS),
    format_func=lambda k: INTENSITY_PRESETS[k]["label"],
)
P = INTENSITY_PRESETS[preset]

users = sb.number_input("Users", 1, 1_000_000, 25, step=1,
                        help="People whose AI workload you want to serve.")
in_tpu = sb.number_input(
    "Input tokens / user / day", 0, 10_000_000_000, int(P["in"]), step=100_000,
    key=f"in_{preset}",
    help="Prompts + context sent to the model, per user per day.",
)
out_tpu = sb.number_input(
    "Output tokens / user / day", 0, 1_000_000_000, int(P["out"]), step=10_000,
    key=f"out_{preset}",
    help="Tokens generated by the model, per user per day.",
)
workdays = sb.number_input("Active days / month", 1.0, 31.0, 22.0, step=1.0,
                           help="22 ≈ business days; 30 for always-on teams.")
growth = sb.number_input(
    "Demand growth / month (%)", -10.0, 50.0, 0.0, step=0.5,
    help="Expect usage to grow (or shrink) month over month.",
)

sb.markdown("---")
sb.header("Cloud comparison")

model = sb.selectbox(
    "Cloud model (list pricing)",
    [m["key"] for m in CLOUD_MODELS],
    format_func=lambda k: f"{CLOUD_BY_KEY[k]['label']} — "
                          f"${CLOUD_BY_KEY[k]['input']:g}/M in, "
                          f"${CLOUD_BY_KEY[k]['output']:g}/M out",
)
M = CLOUD_BY_KEY[model]
ci = sb.number_input("Cloud $ / 1M input tokens", 0.0, 9999.0,
                     float(M["input"]), step=0.1, key=f"ci_{model}")
co = sb.number_input("Cloud $ / 1M output tokens", 0.0, 9999.0,
                     float(M["output"]), step=0.1, key=f"co_{model}")

with sb.expander("Adjustments (cache, batch, overhead)"):
    cache_hit = sb.number_input("Prompt-cache hit rate (%)", 0.0, 100.0, 0.0, step=5.0,
                                help="Cached input tokens are billed at ~10% of base.")
    batch_disc = sb.number_input("Batch / off-peak discount (%)", 0.0, 90.0, 0.0, step=5.0)
    overhead = sb.number_input("Platform overhead (%)", 0.0, 100.0, 0.0, step=5.0,
                               help="Data transfer, platform fees, margin on cloud spend.")
    fixed_fee = sb.number_input("Fixed cloud fees ($/month)", 0.0, 1_000_000.0, 0.0, step=10.0)

    use_mix = sb.checkbox("Use a model mix (weighted average pricing)", value=False)
    mix_users = {}
    if use_mix:
        mix_users = sb.markdown("")  # placeholder to keep layout stable
        cols = sb.columns(2)
        mix_users = {}
        for i, m in enumerate(CLOUD_MODELS):
            with cols[i % 2]:
                mix_users[m["key"]] = sb.number_input(
                    f"Users → {m['label']}", 0, 1_000_000, 0, key=f"mix_{model}_{m['key']}",
                )
        if sum(mix_users.values()) == 0:
            sb.caption("No mix users set — using the single model above.")

sb.markdown("---")
sb.header("Coverage")
local_share = sb.slider(
    "Workload served by your GPUs (%)", 0, 100, 100, step=5,
    help="Hybrid mode: the remainder stays on the cloud API. 100% = all-local.")

# ---- resolve weighted pricing -------------------------------------
pricing = CloudPricing(
    input_price=ci,
    output_price=co,
    cache_hit_pct=cache_hit,
    batch_discount_pct=batch_disc,
    overhead_pct=overhead,
    fixed_monthly=fixed_fee,
)
if use_mix and mix_users and sum(mix_users.values()) > 0:
    total = sum(mix_users.values())
    pricing = CloudPricing(
        input_price=sum(mix_users[m["key"]] * m["input"] for m in CLOUD_MODELS) / total,
        output_price=sum(mix_users[m["key"]] * m["output"] for m in CLOUD_MODELS) / total,
        cache_hit_pct=cache_hit,
        batch_discount_pct=batch_disc,
        overhead_pct=overhead,
        fixed_monthly=fixed_fee,
    )

demand = Demand(
    users=int(users),
    input_tpd_per_user=float(in_tpu),
    output_tpd_per_user=float(out_tpu),
    workdays_per_month=float(workdays),
    growth_pct_per_month=float(growth),
)

monthly_in = demand.in_daily * demand.workdays_per_month
monthly_out = demand.out_daily * demand.workdays_per_month

# =====================================================================
# STEP 2 — Hardware & results (main)
# =====================================================================
st.title("GPU Sizing & Cloud Savings")
st.caption(
    "Compare running your AI workload on owned GPUs vs cloud API spend. "
    "Sizing, TCO, break-even and savings over a chosen period."
)

h1, h2, h3, h4 = st.columns(4)
gpu_key = h1.selectbox(
    "GPU", [g["key"] for g in GPU_PRESETS],
    format_func=lambda k: GPU_BY_KEY[k]["label"],
)
G = GPU_BY_KEY[gpu_key]
price = h2.number_input("Price ($/unit)", 100.0, 1_000_000.0, float(G["price"]), step=100.0,
                        key=f"price_{gpu_key}")
watts = h3.number_input("Power (W)", 25.0, 4000.0, float(G["watts"]), step=10.0,
                        key=f"watts_{gpu_key}")
cap_in = h4.number_input("Sustained in tok/s/GPU", 1.0, 1_000_000.0, float(G["in_tps"]),
                         step=10.0, key=f"intps_{gpu_key}",
                         help="Prefill throughput. Calibrate to your own vLLM benchmark — this is the biggest lever in the calc.")
cap_out = h4.number_input("Sustained out tok/s/GPU", 0.1, 100_000.0, float(G["out_tps"]),
                          step=1.0, key=f"outtps_{gpu_key}",
                          help="Decode throughput per GPU at your model size.")

p1, p2, p3, p4, p5 = st.columns(5)
elec = p1.number_input("Electricity ($/kWh)", 0.0, 5.0, 0.15, step=0.01)
pue = p2.number_input("PUE", 1.0, 3.0, 1.2, step=0.05)
duty = p3.number_input("Duty hours/day", 1.0, 24.0, 24.0, step=1.0)
pdays = p4.number_input("Power days/month", 1.0, 31.0, 30.0, step=1.0)
hosting = p5.number_input("Maintenance ($/GPU/mo)", 0.0, 10_000.0, 50.0, step=10.0)

o1, o2, o3, o4 = st.columns(4)
target_util = o1.number_input("Target utilization (%)", 10.0, 95.0, 70.0, step=5.0,
                              help="Size the fleet so demand uses ≤ this share of capacity.")
life = o2.number_input("Hardware life (months)", 6, 120, 36, step=6)
residual = o3.number_input("Residual value at end of life (%)", 0.0, 100.0, 20.0, step=5.0)
disc = o4.number_input("Discount rate (%/yr)", 0.0, 30.0, 8.0, step=1.0)

st.markdown("---")

months = st.slider("Comparison period (months)", 6, 120, 36, step=6)

gpu = GpuSpec(gpu_key, GPU_BY_KEY[gpu_key]["label"], float(price), float(watts),
              float(cap_in), float(cap_out))
own = Ownership(
    duty_hours_per_day=float(duty),
    power_days_per_month=float(pdays),
    pue=float(pue),
    elec_rate=float(elec),
    hosting_per_gpu_month=float(hosting),
    target_utilization_pct=float(target_util),
    hardware_life_months=int(life),
    residual_pct=float(residual),
    discount_rate_pct=float(disc),
)

res = simulate(demand, pricing, gpu, own, int(months), local_share / 100.0)

# ---------------------------------------------------------------- KPIs
be = res["break_even_month"]
st.header("2 · Your results")

k1, k2, k3, k4, k5, k6 = st.columns(6)
k1.metric(
    "Break-even (vs all-cloud)",
    f"Month {be}" if be else f"> {int(months)} mo",
    help="First month where cumulative local cost falls below cumulative cloud spend.",
)
k2.metric(
    f"Savings over {int(months)} mo",
    usd(res["savings"]),
    delta=f"{res['savings_pct']:+.1f}% vs all-cloud" if res["cloud_full_total"] else None,
)
k3.metric("Local TCO (period)", usd(res["tco"]),
          help="Total cost of ownership: capex + opex − terminal fleet value.")
k4.metric("All-cloud cost (period)", usd(res["cloud_full_total"]))
k5.metric("GPUs required (peak)", f"{res['peak_units']}")
k6.metric("Cloud run-rate (final mo)", usd(res["cloud_last"]["total"]),
          help="What the cloud would charge for the portion not covered locally, at month end.")

# ---------------------------------------------------------------- charts
fig = go.Figure()
ms = list(range(1, months + 1))
fig.add_trace(go.Scatter(
    x=ms, y=res["cum_cloud_full"], name="All cloud",
    line=dict(color="#5b6270", width=2.5),
))
fig.add_trace(go.Scatter(
    x=ms, y=res["cum_local_full"], name="All local",
    line=dict(color="#00C2DE", width=2.5),
))
if 0 < res["local_share"] < 1:
    fig.add_trace(go.Scatter(
        x=ms, y=res["cum_hybrid"], name=f"Hybrid ({int(res['local_share']*100)}% local)",
        line=dict(color="#C1A968", width=2.5, dash="dot"),
    ))
if be:
    fig.add_vline(x=be, line=dict(color="#0f9d58", width=1.5, dash="dash"))
    fig.add_annotation(x=be, y=res["cum_cloud_full"][be - 1],
                       text=f" break-even · mo {be}", showarrow=True,
                       arrowhead=2, ax=-60, ay=-30, font=dict(size=12, color="#0f9d58"))
fig.update_layout(
    title="Cumulative cost",
    yaxis_title="USD",
    legend=dict(orientation="h", y=1.12),
    margin=dict(l=10, r=10, t=60, b=10),
    height=420,
)
st.plotly_chart(fig, width="stretch")

m1, m2 = st.columns(2)
fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=ms, y=res["cloud_full"], name="Cloud monthly",
                          line=dict(color="#5b6270", width=2)))
fig2.add_trace(go.Scatter(x=ms, y=[a + b for a, b in zip(res["hybrid_local"], res["hybrid_cloud"])],
                          name="Local monthly (incl. capex)",
                          line=dict(color="#00C2DE", width=2)))
fig2.update_layout(title="Monthly cost", yaxis_title="USD",
                   legend=dict(orientation="h", y=1.12),
                   margin=dict(l=10, r=10, t=50, b=10), height=360)
with m1:
    st.plotly_chart(fig2, width="stretch")

fig3 = go.Figure()
fig3.add_trace(go.Scatter(x=ms, y=res["hybrid_units"], name="GPUs (local)",
                          line=dict(color="#C1A968", width=2)))
fig3.update_layout(title="Fleet size", yaxis_title="GPUs", yaxis_tickvals=list(range(0, res["peak_units"] + 1, max(1, res["peak_units"] // 6))),
                   margin=dict(l=10, r=10, t=50, b=10), height=360,
                   legend=dict(orientation="h", y=1.12))
with m2:
    st.plotly_chart(fig3, width="stretch")

# ---------------------------------------------------------------- sizing
s1, s2, s3, s4 = st.columns(4)
s1.metric("GPUs at month 1", f"{res['units_month1']}")
s2.metric("Utilization @ peak", f"{res['peak_utilization']*100:.0f}%")
s3.metric("Energy / GPU / month", usd(res["energy_per_gpu_month"]))
s4.metric("NPV of local path", usd(res["npv"]),
          help="Time-discounted TCO at the chosen discount rate.")

# ---------------------------------------------------------------- detail
with st.expander("Cost calculation detail", expanded=False):
    d1, d2 = st.columns(2)
    last_m = int(months)
    with d1:
        st.markdown("**Cloud (final month, full workload)**")
        cl = res["cloud_last"]
        tbl = pd.DataFrame(
            {
                "": ["Input tokens / mo", "Output tokens / mo",
                     "Input cost", "Output cost", "Adjustments (cache/batch/overhead)",
                     "Total (incl. fixed fees)"],
                "Value": [
                    f"{cl['tokens_in']/1e6:,.1f} M",
                    f"{cl['tokens_out']/1e6:,.1f} M",
                    usd_full(cl["input"]),
                    usd_full(cl["output"]),
                    usd_full(cl["total"] - cl["input"] - cl["output"]),
                    usd_full(cl["total"]),
                ],
            }
        )
        st.dataframe(tbl, width="stretch", hide_index=True)
    with d2:
        st.markdown("**Local fleet (period totals)**")
        tbl2 = pd.DataFrame(
            {
                "": ["Hardware purchases (gross)", "Resale credits",
                     "Terminal fleet value", "Energy (period)",
                     "Maintenance/hosting", "TCO (purchases + opex − terminal)",
                     "NPV"],
                "Value": [
                    usd_full(res["gross_purchases"]),
                    usd_full(res["retirement_credits"]),
                    usd_full(res["terminal_value"]),
                    usd_full(sum(o - a * own.hosting_per_gpu_month
                                 for o, a in zip(res["hybrid_opex"], res["hybrid_units"]))),
                    usd_full(sum(a * own.hosting_per_gpu_month
                                 for a in res["hybrid_units"])),
                    usd_full(res["tco"]),
                    usd_full(res["npv"]),
                ],
            }
        )
        st.dataframe(tbl2, width="stretch", hide_index=True)

    st.markdown("**Paths over the period**")
    tbl3 = pd.DataFrame(
        {
            "Path": ["All cloud", "All local",
                     f"Hybrid ({int(res['local_share']*100)}% local)"],
            "Total cost": [usd(res["cloud_full_total"]), usd(res["local_full_total"]),
                           usd(res["hybrid_total"])],
            "Savings vs all-cloud": ["—", usd(res["cloud_full_total"] - res["local_full_total"]),
                                     usd(res["savings"])],
        }
    )
    st.dataframe(tbl3, width="stretch", hide_index=True)

with st.expander("Sensitivity — break-even under other assumptions", expanded=False):
    rows = sensitivity(res, demand, pricing, gpu, own, int(months), local_share / 100.0)
    st.dataframe(
        pd.DataFrame(
            {
                "Scenario": [r["label"] for r in rows],
                "Assumptions": [r["note"] for r in rows],
                "Break-even": [
                    f"Month {r['break_even']}" if r["break_even"] else f"> {int(months)} mo"
                    for r in rows
                ],
            }
        ),
        width="stretch", hide_index=True,
    )

# ---------------------------------------------------------------- export
buf = io.StringIO()
df = pd.DataFrame(
    {
        "month": ms,
        "cloud_total": [round(v, 2) for v in res["cum_cloud_full"]],
        "local_total": [round(v, 2) for v in res["cum_local_full"]],
        "hybrid_total": [round(v, 2) for v in res["cum_hybrid"]],
        "hybrid_gpus": res["hybrid_units"],
        "hybrid_opex": [round(v, 2) for v in res["hybrid_opex"]],
        "hybrid_capex": [round(v, 2) for v in res["hybrid_capex"]],
    }
)
buf.write(df.to_csv(index=False))
st.download_button(
    "⬇️ Export monthly series (CSV)",
    data=buf.getvalue(),
    file_name=f"gpu-sizing_{gpu_key}_{int(months)}mo.csv",
    mime="text/csv",
)

st.markdown(
    "<div style='color:#888;font-size:12px;margin-top:18px'>"
    "Estimates only: GPU tokens/sec depend heavily on model size, batching and "
    "context length — calibrate against your own vLLM benchmarks. Cloud prices are "
    "2026 list prices and change frequently. Not financial advice.</div>",
    unsafe_allow_html=True,
)
